### ISSUE TITLE
Change the spacing of the redo and insert icons on the record screen

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#433] opened 2016-04-26 13:56 UTC
## User Story
As a translator, I need the spacing of the redo and insert icons on the record screen to be increased in order to avoid accidentally hitting the wrong button.   

## Details.
I've observed that about half the users hit the wrong button, because the spacing of the icons was too close or the targeting of the zones was not large enough.  They would either hit the wrong button unintentionally or have to tap several times until they hit the button at all.  BTW These users were brand new to the tablet experience.

**Comment by vleong2332** [comment] 2016-07-26 14:06
Duplicate of #515.

**Closed by vleong2332** 2016-07-26 14:06 UTC
